PR
igorogerchuk/memcrab-test pull request #1
Opened 2020-04-03 19:20 UTC by igorogerchuk

2020-04-06 14:51 UTC, max-mykhailenko requested changes

2020-04-06 14:51 UTC, max-mykhailenko commented on flow-coverage/assets/codemirror-annotatescrollbar-addon.js
> +// CodeMirror, copyright (c) by Marijn Haverbeke and others
всю папку  flow-coverage добавь в git ignore

2020-04-06 14:51 UTC, max-mykhailenko commented on package.json
> +    "@craco/craco": "^5.6.4",
В принципе никогда не понадобится. Просто будет конфиг с нуля и все

2020-04-06 14:51 UTC, max-mykhailenko commented on package.json
> +    "redux-devtools-extension": "^2.13.8",
Вроде как не нужно ставить как модуль, лучше тянуть с window

2020-04-06 14:51 UTC, max-mykhailenko commented on src/components/Array/Array.jsx
> +export default connect<
используй силу, используй хуки

2020-04-06 14:51 UTC, max-mykhailenko commented on src/components/Inputs/Inputs.jsx
> +    onSaveParams({ n: Number(n), x: Number(x) });
Если ты попробуешь передать какие то другие параметры, то flow тебе об этом скажет?

2020-04-06 14:51 UTC, max-mykhailenko commented on src/redux/reducer.js
> +      action.payload.cellsIds.forEach(cellId => delete withoutDeleted[cellId]);
Сможешь это написать более функционально?

2020-04-06 14:51 UTC, max-mykhailenko commented on src/redux/selectors.js
>      for (let j = 0; j < cellsIds[0].length; j++) {
сможешь переписать без for?

2020-04-06 14:51 UTC, max-mykhailenko commented on src/redux/store.js
> +  devToolsEnhancer()
почему решил одно заменить на другое?

2020-04-16 19:55 UTC, igorogerchuk commented on package.json
> +    "@craco/craco": "^5.6.4",
@max-mykhailenko ты сказал мне использовать styleName вместо className, для этого  нужен react-css-modules, а чтоб его подключить к create-react-app нужен craco, другого способа я не нашел

2020-04-16 19:55 UTC, igorogerchuk commented on flow-coverage/assets/codemirror-annotatescrollbar-addon.js
> +// CodeMirror, copyright (c) by Marijn Haverbeke and others
добавил

2020-04-16 19:57 UTC, igorogerchuk commented on package.json
> +    "redux-devtools-extension": "^2.13.8",
так и было, вернул к старой версии, это удалил

2020-04-16 20:11 UTC, igorogerchuk commented on src/components/Array/Array.jsx
> +export default connect<
@max-mykhailenko имеешь в виду использовать useMemo вместо memo?

2020-04-16 20:49 UTC, igorogerchuk commented on src/components/Inputs/Inputs.jsx
> +    onSaveParams({ n: Number(n), x: Number(x) });
действительно, не скажет, можно Number обернуть все что угодно. Что делать?) Добавить проверку перед вызовом, типа
if(+n && +x) {...} ?

2020-04-16 21:20 UTC, igorogerchuk commented on src/redux/store.js
> +  devToolsEnhancer()
экспериментировал) уже вернул как было

2020-04-17 13:25 UTC, igorogerchuk commented on src/redux/reducer.js
> +      action.payload.cellsIds.forEach(cellId => delete withoutDeleted[cellId]);
@max-mykhailenko может такой вариант будет лучше?
`const { cellsIds } = action.payload;
 const withoutDeleted: CellsState = Object.keys(state).reduce(
        (
          acc: { [id: string]: { id: string, amount: number } },
          cellId: string
        ) =>
          cellsIds.includes(cellId) ? acc : { ...acc, [cellId]: state[cellId] },
        {}
  );`
чтоб не копировать state полностью и потом удалять из него полученные id, а сразу копировать только те id, которых нет в полученных

2020-04-17 18:46 UTC, igorogerchuk commented on src/redux/selectors.js
>      for (let j = 0; j < cellsIds[0].length; j++) {
@max-mykhailenko так лучше?
export const AvarageRow = createSelector<State, *, *, *, *>(
  [getRows, getCells],
  (rows, cells) => {
    const cellsIds = Object.keys(rows).map((rowId: string) => rows[rowId]);
    const m = cellsIds.length;
    const n = cellsIds[0].length;
    const avarageRow = cellsIds.reduce(
      (acc, row) =>
        row.map((id, index) => (acc[index] += cells[row[index]].amount / m)),
      new Array(n).fill(0)
    );
    return avarageRow;
  }
);

2020-04-17 19:36 UTC, igorogerchuk commented on src/redux/selectors.js
>      for (let j = 0; j < cellsIds[0].length; j++) {
и так для getSumColumn
export const getSumColumn = createSelector<State, *, *, *, *>(
  [getRows, getCells],
  (rows, cells) => {
    const cellsIds = Object.keys(rows).map((rowId: string) => rows[rowId]);
    const sumColumn = cellsIds.map((row) =>
      row.reduce((acc, id) => (acc += cells[id].amount), 0)
    );
    return sumColumn;
  }
);

2020-04-19 18:08 UTC, max-mykhailenko requested changes

2020-04-19 18:08 UTC, max-mykhailenko commented on src/redux/selectors.js
>      for (let j = 0; j < cellsIds[0].length; j++) {
Было бы правильно прямо в коде, а не в комментариях

2020-04-19 18:08 UTC, max-mykhailenko commented on flow-coverage/assets/codemirror-annotatescrollbar-addon.js
> +// CodeMirror, copyright (c) by Marijn Haverbeke and others
Таки не сработало, так как все до сих пор здесь

2020-04-19 18:08 UTC, max-mykhailenko commented on src/components/Array/Array.jsx
> +export default connect<
нет, имею ввиду использование useSelector https://react-redux.js.org/api/hooks#useselector

2020-04-19 18:08 UTC, max-mykhailenko commented on src/components/Inputs/Inputs.jsx
> +    onSaveParams({ n: Number(n), x: Number(x) });
Вопрос в другом, как точно затипизирован flow, то есть позволит ли он передать в N стоку?

2020-04-19 18:08 UTC, max-mykhailenko commented on src/redux/reducer.js
> +      action.payload.cellsIds.forEach(cellId => delete withoutDeleted[cellId]);
Меняй срвзу в коде, foreach с удаление всяко хуже

2020-04-24 05:47 UTC, closed without merging